I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 7, in script
    define n = narrator_nvl
  File "game/script.rpy", line 7, in <module>
    define n = narrator_nvl
NameError: name 'narrator_nvl' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 7, in script
    define n = narrator_nvl
  File "D:\Downloads\renpy-7.3.2-sdk\renpy\ast.py", line 2106, in execute
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "D:\Downloads\renpy-7.3.2-sdk\renpy\python.py", line 2028, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 7, in <module>
    define n = narrator_nvl
NameError: name 'narrator_nvl' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.2.320
VisualNovel 1.0
Sun Sep 29 13:21:15 2019
